# 线上配置文件
# @author <a href="https://github.com/lidjm">程序员鱼皮</a>
# @from <a href="https://djm.icu">编程导航知识星球</a>
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/yuapi
    username: root
    password: 123456